name: cowsay workflow

on: push

jobs:
    cowsay:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the repo
          uses: actions/checkout@v4

        - name: dragon job
          run: |
            chmod +x ./script.sh
            ./script.sh